# GitHub Sponsors configuration
# This project is part of a BMW x ISM academic field project
# For partnership or sponsorship inquiries, please open an issue

github: []
# Project sponsored by:
# - BMW Group (Corporate Partner)
# - International School of Management (ISM) (Academic Institution)
